config/routes.rb
Rails.application.routes.draw do
  resources :groups
  resources :hours
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :friendships
  get '/signup',  to: 'users#new'
  get '/signin',  to: 'sessions#new'
  get '/signout', to: 'sessions#destroy'
  get '/external', to: 'hours#external'
  get '/profile', to: 'users#profile'
  get '/alluser', to: 'users#alluser'
  get '/friends', to: 'users#friends'
  root to: 'users#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/hour.rb
class Hour < ApplicationRecord
  belongs_to :user
  belongs_to :group, optional: true
  validates :name, presence: true
  validates :amount, presence: true, inclusion: { in: 0..200 }
end

app/controllers/hours_controller.rb
class HoursController < ApplicationController
  before_action :set_hour, only: %i[show edit update destroy]

  # GET /hours
  # GET /hours.json
  def index
    @current_user ||= User.find_by_remember_token(cookies[:remember_token])
    @hours = Hour.where(user_id: @current_user.id).where.not(group_id: nil).order('created_at DESC').includes(:group)
    @time = @hours.to_a.map { |x| x[:amount] }.sum
  end

  # GET /hours/1
  # GET /hours/1.json
  def show; end

  def external
    @current_user ||= User.find_by_remember_token(cookies[:remember_token])
    @hours = Hour.where(user_id: @current_user.id, group_id: nil).order('created_at DESC').includes(:group)
    @time = @hours.to_a.map { |x| x[:amount] }.sum
  end

  # GET /hours/new
  def new
    @group_options = Group.all.map { |u| [u.name, u.id] }
    @hour = Hour.new
  end

  # GET /hours/1/edit
  def edit; end

  # POST /hours
  # POST /hours.json
  def create
    @hour = Hour.new(hour_params)
    @current_user ||= User.find_by_remember_token(cookies[:remember_token])
    @hour.user_id = @current_user.id
    @group_options = Group.all.map { |u| [u.name, u.id] }

    respond_to do |format|
      if @hour.save
        format.html { redirect_to @hour, notice: 'Hour was successfully created.' }
        format.json { render :show, status: :created, location: @hour }
      else
        format.html { render :new }
        format.json { render json: @hour.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hours/1
  # PATCH/PUT /hours/1.json
  def update
    respond_to do |format|
      if @hour.update(hour_params)
        format.html { redirect_to @hour, notice: 'Hour was successfully updated.' }
        format.json { render :show, status: :ok, location: @hour }
      else
        format.html { render :edit }
        format.json { render json: @hour.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hours/1
  # DELETE /hours/1.json
  def destroy
    @hour.destroy
    respond_to do |format|
      format.html { redirect_to hours_url, notice: 'Hour was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_hour
    @hour = Hour.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def hour_params
    params.require(:hour).permit(:name, :user_id, :amount, :group_id)
  end
end

app/helpers/hours_helper.rb
module HoursHelper
end

app/views/hours/_form.html.erb
<%= form_with(model: hour, local: true) do |form| %>
  <% if hour.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(hour.errors.count, "error") %> prohibited this hour from being saved:</h2>

      <ul>
        <% hour.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="text-center">
  <div class="field text-center d-inline-block">
    <%= form.text_field :name, placeholder:"name", class: "border-top-0 border-left-0 border-right-0 pt-2 pb-2"%><br>
    <%= form.number_field :amount, placeholder:"amount", class: "border-0 pt-2 pb-2" %>
    <%= form.label :group %>
    <%= form.select(:group_id, @group_options, { include_blank: true }) %>
  </div>
  </div>
  <br>

  <div class="actions text-center">
    <%= form.submit%><br><br>
    <%= link_to 'Back', hours_path%>
  </div>
  
<% end %>

app/views/hours/edit.html.erb
<h1>Editing Hour</h1>

<%= render 'form', hour: @hour %>

<%= link_to 'Show', @hour %> |
<%= link_to 'Back', hours_path %>

app/views/hours/external.html.erb
<body class="bg-light">
<header class="blog-header py-3 bg-nblg">
    <div class="row flex-nowrap justify-content-between align-items-center">
        <div class="col-4 pt-1">
            <%= link_to 'My Profile', '/profile', class:"text-white ml-2"%>
        </div>
        <div class="col-4 text-center">
            <h1 class="blog-header-logo text-white" href="#">External Hours</h1>
        </div>
        <div class="col-4 d-flex justify-content-end align-items-center">
            <%= link_to "Sign out", signout_path, class: "btn btn-sm btn-outline-secondary text-white mr-2"%><br>
        </div>
    </div>
</header>
<p class= "bg-white pb-2 pt-2 pr-2 pl-2"> Total Hours <strong class="float-right"><%= @time %>hrs</strong> </p>
<% @hours.each do |hour| %>
<div class="media pt-2 pb-2 text-muted bg-white">
    <p class="lh-125 mb-0 media-body small ml-2"> <strong class="d-block text-gray-dark"><%= hour.name %> <strong class="float-right mr-2"><%= hour.amount %>hrs</strong></strong><br><%= hour.created_at %></p>
</div>
<br>
<% end %>
<%= link_to 'New Hour', new_hour_path %>
</body>

app/views/hours/index.html.erb
<body class="bg-light">
<header class="blog-header py-3 bg-nblg">
    <div class="row flex-nowrap justify-content-between align-items-center">
        <div class="col-4 pt-1">
            <%= link_to 'My Profile', '/profile', class:"text-white ml-2"%>
        </div>
        <div class="col-4 text-center">
            <h1 class="blog-header-logo text-white" href="#">Hours</h1>
        </div>
        <div class="col-4 d-flex justify-content-end align-items-center">
            <%= link_to "Sign out", signout_path, class: "btn btn-sm btn-outline-secondary text-white mr-2"%><br>
        </div>
    </div>
</header>
<p class= "bg-white pb-2 pt-2 pr-2 pl-2"> Total Hours <strong class="float-right"><%= @time %>hrs</strong> </p>
<% @hours.each do |hour| %>
<div class="media pt-2 pb-2 text-muted bg-white">
    <img src="<%=(url_for(hour.group.icon))%>" alt="" class="ml-2 mr-2 rounded" width="50" height="50"/>
    <p class="lh-125 mb-0 media-body small"> <strong class="d-block text-gray-dark"><%= hour.name %> <strong class="float-right mr-2"><%= hour.amount %>hrs</strong></strong><br><%= hour.created_at %></p>
</div>
<br>
<% end %>
<%= link_to 'New Hour', new_hour_path %>
</body>

app/views/hours/new.html.erb
<header class="blog-header py-3 bg-nblg">
    <div class="row flex-nowrap justify-content-between align-items-center">
        <div class="col text-center">
            <h1 class="blog-header-logo text-white">Add New Hour</h1>
        </div>
    </div>
</header>
<br>
<%= render 'form', hour: @hour %>

app/views/hours/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @hour.name %>
</p>

<p>
  <strong>User:</strong>
  <%= @hour.user.name %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @hour.amount %>
</p>

<p>
  <strong>group:</strong>
  <% if @hour.group.nil? %>
   none
  <% else %>
  <%= @hour.group.name %>
  <% end %>
</p>

<%= link_to 'Back', hours_path %>