config/routes.rb
Rails.application.routes.draw do
  resources :groups
  resources :hours
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :friendships
  get '/signup',  to: 'users#new'
  get '/signin',  to: 'sessions#new'
  get '/signout', to: 'sessions#destroy'
  get '/external', to: 'hours#external'
  get '/profile', to: 'users#profile'
  get '/alluser', to: 'users#alluser'
  get '/friends', to: 'users#friends'
  root to: 'users#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/group.rb
class Group < ApplicationRecord
  has_one_attached :icon
  has_many :hours
  validates :name, presence: true
  validates :icon, presence: true, blob: { content_type: ['image/jpg', 'image/jpeg', 'image/png'], size_range: 1..3.megabytes }
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: %i[show edit update destroy]

  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all.order('name ASC')
    @index ||= User.find_by_remember_token(cookies[:remember_token])
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
    @hours = Hour.where(group_id: @group.id).order('created_at DESC').includes(:user)
    @hour = @hours.to_a.map { |x| x[:amount] }.sum
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit; end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_group
    @group = Group.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def group_params
    params.require(:group).permit(:name, :icon)
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_with(model: group, local: true) do |form| %>
  <% if group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
        <% group.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

    <div class="field">
    <%= form.label 'Profile Photo' %>
    <%= form.file_field :icon, class:"border-bottom pt-2 pb-2" %><br>
    <%= form.text_field :name, placeholder:"name", class: "border-0 pt-2 pb-2" %>
  </div>

  <div class="actions text-center">
    <%= form.submit%><br><br>
    <%= link_to 'Back', groups_path%>
  </div>
<% end %>

app/views/groups/edit.html.erb
<h1>Editing Group</h1>

<%= render 'form', group: @group %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

app/views/groups/index.html.erb
<body class="bg-light">
<header class="blog-header py-3 bg-primary">
    <div class="row flex-nowrap justify-content-between align-items-center">
        <div class="col-4 pt-1">
            <%= link_to 'My Profile', '/profile', class:"text-white ml-2"%>
        </div>
        <div class="col-4 text-center">
            <h1 class="blog-header-logo text-white" href="#">All Groups</h1>
        </div>
        <div class="col-4 d-flex justify-content-end align-items-center">
            <%= link_to "Sign out", signout_path, class: "btn btn-sm btn-outline-secondary text-white mr-2"%><br>
        </div>
    </div>
</header>
<br>
<% @groups.each do |group| %>
<a href=<%=(url_for(group))%>>
<div class="media pt-2 pb-2 text-muted bg-white">
  <img src="<%=(url_for(group.icon))%>" alt="" class="ml-2 mr-2 rounded" width="50" height="50"/>
  <p class="lh-125 mb-0 media-body small ml-2"> <strong class="d-block text-gray-dark"><%= group.name %></strong><br><%= group.created_at %></p>
</div>
<br>
<% end %>
</a>
<%= link_to 'New Group', new_group_path %>
</body>

app/views/groups/new.html.erb
<header class="blog-header py-3 bg-nblg">
    <div class="row flex-nowrap justify-content-between align-items-center">
        <div class="col text-center">
            <h1 class="blog-header-logo text-white">New Group</h1>
        </div>
    </div>
</header>
<br>
<%= render 'form', group: @group %>

app/views/groups/show.html.erb
<body class="bg-light">
<header class="blog-header py-3 bg-primary">
    <div class="row flex-nowrap justify-content-between align-items-center">
        <div class="col-4 pt-1">
            <%= link_to 'My Profile', '/profile', class:"text-white ml-2"%>
        </div>
        <div class="col-4 text-center">
            <h1 class="blog-header-logo text-white" href="#"><%= @group.name %> Hours</h1>
        </div>
        <div class="col-4 d-flex justify-content-end align-items-center">
            <%= link_to "Sign out", signout_path, class: "btn btn-sm btn-outline-secondary text-white mr-2"%><br>
        </div>
    </div>
</header>
<p class= "bg-white pb-2 pt-2 pr-2 pl-2"> Total Hours <strong class="float-right"><%= @hour %>hrs</strong> </p>
<% @hours.each do |hour| %>
<div class="media pt-2 pb-2 text-muted bg-white">
    <img src="<%=(url_for(hour.group.icon))%>" alt="" class="ml-2 mr-2 rounded" width="50" height="50"/>
    <p class="lh-125 mb-0 media-body small"> <strong class="d-block text-gray-dark"><%= hour.name %> <strong class="float-right mr-2"><%= hour.amount %>hrs</strong></strong><br><%= hour.created_at %><strong class="float-right mr-2"><%= hour.user.name %></strong></p>
</div>
<br>
<% end %>
</body>