config/routes.rb
Rails.application.routes.draw do
  resources :groups
  resources :hours
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :friendships
  get '/signup',  to: 'users#new'
  get '/signin',  to: 'sessions#new'
  get '/signout', to: 'sessions#destroy'
  get '/external', to: 'hours#external'
  get '/profile', to: 'users#profile'
  get '/alluser', to: 'users#alluser'
  get '/friends', to: 'users#friends'
  root to: 'users#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_one_attached :avatar
  has_many :hours
  has_many :friendships
  has_many :friends, through: :friendships
  before_save :create_remember_token
  validates :name, presence: true
  validates :avatar, presence: true, blob: { content_type: ['image/jpg', 'image/jpeg', 'image/png'], size_range: 1..3.megabytes }

  private

  def create_remember_token
    self.remember_token = SecureRandom.urlsafe_base64
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]
  layout 'profile', only: [:profile]
  include SessionsHelper
  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  def alluser
    @users = User.all
  end

  def friends
    @users = User.all
    @friends ||= User.find_by_remember_token(cookies[:remember_token])
  end

  def profile
    @profile ||= User.find_by_remember_token(cookies[:remember_token])
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @hours = Hour.where(user_id: @user.id).order('created_at DESC').includes(:group)
    @time = @hours.to_a.map { |x| x[:amount] }.sum
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit; end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        sign_in @user
        format.html { redirect_to '/profile', notice: 'User was successfully created.' }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:name, :avatar)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label 'Profile Photo' %>
    <%= form.file_field :avatar %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions text-center">
    <%= form.submit %><br><br>
    <%= link_to 'Back', users_path %>
  </div>
<% end %>

app/views/users/alluser.html.erb
<body class="bg-light">
<header class="blog-header py-3 bg-nblg">
    <div class="row flex-nowrap justify-content-between align-items-center">
        <div class="col-4 pt-1">
            <%= link_to 'My Profile', '/profile', class:"text-white ml-2"%>
        </div>
        <div class="col-4 text-center">
            <h1 class="blog-header-logo text-white" href="#">All Users</h1>
        </div>
        <div class="col-4 d-flex justify-content-end align-items-center">
            <%= link_to "Sign out", signout_path, class: "btn btn-sm btn-outline-secondary text-white mr-2"%><br>
        </div>
    </div>
</header>
<br>

<% @users.each do |user| %>
  <% if user.name != current_user.name %>
  <div class="media pt-2 pb-2 text-muted bg-white">
    <p class="lh-125 mb-0 media-body small ml-2"> <strong class="d-block text-gray-dark"><%= user.name %>
    <% if Friendship.where(:user_id => current_user.id, :friend_id => user.id).exists?%>
      <%= link_to "Unfollow", friendship_path(current_user.friendships.find_by_friend_id(user)), :method => :delete, class: "float-right mr-2" %>
    <% else %>
      <%= link_to "Follow", friendships_path(:friend_id => user), :method => :post, class: "float-right mr-2"%>
    </p>
    <% end %>
</div>
 <br>
  <% end %> 
<% end %>
</body>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/friends.html.erb
<body class="bg-light">
<header class="blog-header py-3 bg-nblg">
    <div class="row flex-nowrap justify-content-between align-items-center">
        <div class="col-4 pt-1">
            <%= link_to 'My Profile', '/profile', class:"text-white ml-2"%>
        </div>
        <div class="col-4 text-center">
            <h1 class="blog-header-logo text-white" href="#">Friends</h1>
        </div>
        <div class="col-4 d-flex justify-content-end align-items-center">
            <%= link_to "Sign out", signout_path, class: "btn btn-sm btn-outline-secondary text-white mr-2"%><br>
        </div>
    </div>
</header>
<br>

<% @friends.friendships.each do |friendship| %>
  <%= link_to friendship.friend do %>
  <div class="media pt-2 pb-2 text-muted bg-white">
    <img src="<%=(url_for(friendship.friend.avatar))%>" alt="" class="ml-2 mr-2 rounded" width="50" height="50"/>
    <p class="lh-125 mb-0 media-body small ml-3 mt-1"> <strong class="d-block text-gray-dark h3 "><%= friendship.friend.name %></strong></p>   
  </div>
  <% end %>
<% end %>

app/views/users/index.html.erb
<div class="text-center">
<%= image_tag("clock1.png", :alt => "rss feed", :width => "72",  :height => "72") %>
<h1>Times</h1>
<br>
<% if signed_in? %>
<%= link_to "Sign out", signout_path%><br>
<%= link_to 'My Profile', 'profile'%>
<% else %>
<%= link_to 'LOG IN', '/signin', class: "btn btn-lg btn-primary btn-block text-white" %>
<%= link_to 'SIGN UP', '/signup', class: "btn btn-lg btn-block" %>
<% end %>
</div>

app/views/users/new.html.erb
<header class="blog-header py-3 bg-nblg">
    <div class="row flex-nowrap justify-content-between align-items-center">
        <div class="col text-center">
            <h1 class="blog-header-logo text-white">Sign Up</h1>
        </div>
    </div>
</header>
<br>

<%= render 'form', user: @user %>

app/views/users/profile.html.erb
<div class="text-center">
<img src="<%=(url_for(@profile.avatar))%>" class="ml-2 mr-2 mb-3 rounded-circle" width="80" height="80"/>
<br>
<h4 class="mb-3 text-white">
  <%= @profile.name %>
</h4>

<%= link_to 'All my hours', hours_path, class: "d-block pt-3 pb-3 text-white" %>
<%= link_to 'All my  external hours', '/external', class: "d-block pt-3 pb-3 border-top border-gray text-white" %>
<%= link_to 'All groups', groups_path, class: "d-block pt-3 pb-3 border-top border-gray text-white"%> 
<%= link_to 'All users', '/alluser', class: "d-block pt-3 pb-3 border-top border-gray text-white" %>
<%= link_to 'Friends', '/friends', class: "d-block pt-3 pb-3 border-top border-gray text-white" %>
<%= link_to "Sign out", signout_path, class: "d-block pt-3 pb-3 border-top border-gray text-white" %>
</div>

app/views/users/show.html.erb
<body class="bg-light">
<header class="blog-header py-3 bg-nblg">
    <div class="row flex-nowrap justify-content-between align-items-center">
        <div class="col-4 pt-1">
            <%= link_to 'My Profile', '/profile', class:"text-white ml-2"%>
        </div>
        <div class="col-4 text-center">
            <h1 class="blog-header-logo text-white" href="#"><%= @user.name %> Hours</h1>
        </div>
        <div class="col-4 d-flex justify-content-end align-items-center">
            <%= link_to "Sign out", signout_path, class: "btn btn-sm btn-outline-secondary text-white mr-2"%><br>
        </div>
    </div>
</header>
<br>

<p class= "bg-white pb-2 pt-2 pr-2 pl-2"> Total Hours <strong class="float-right"><%= @time %>hrs</strong> </p>
<% @hours.each do |hour| %>
<div class="media pt-2 pb-2 text-muted bg-white">
    <img src="<%=(url_for(hour.group.icon))%>" alt="" class="ml-2 mr-2 rounded" width="50" height="50"/>
    <p class="lh-125 mb-0 media-body small"> <strong class="d-block text-gray-dark"><%= hour.name %> <strong class="float-right mr-2"><%= hour.amount %>hrs</strong></strong><br><%= hour.created_at %></p>
</div>
<br>
<% end %>